### ISSUE TITLE
Build failure for R-universe

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow2#224]
R-universe currently only has source code.

https://github.com/r-universe/genentech/actions/runs/5883353866

**Comment by gravesti** [comment]
Basically I think we might need to precompile the vignettes:
https://github.com/r-universe-org/help#how-to-publish-vignettesarticles-which-require-custom-softwaretokens-to-render

Alternatively make all vignettes only execute if cmdstan is available. Something like this in each vignette

```r
knitr::opts_chunk$set(
  eval = is.character(cmdstanr::cmdstan_version(error_on_NA = FALSE))
)
```

`instantiate` package has a trick we could copy, but they are in a different situation because they only suggest cmdstanr.

1. At build time it runs configure script: https://github.com/wlandau/instantiate/blob/main/configure
2. This calls another script which installs `cmdstan` only if a certain environment variable is set: https://github.com/wlandau/instantiate/blob/main/inst/cmdstan.R
