### ISSUE TITLE
fix GHA on windows

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow2#281]

**Comment by mattsecrest** [comment]
cmdstan not able to install b/c of `pacman` problems. Not sure why a new issue.

**Comment by mattsecrest** [comment]
- [ ] https://github.com/msys2/setup-msys2

**Comment by gravesti** [comment]
The version of Rtools43 being installed has a bug. The action uses the version [here](https://github.com/r-hub/rtools43/releases)  so we just need to wait for an update. I've filed an issue https://github.com/r-hub/rtools43/issues/2

The issue is the certificates are not available. A possible work around is described in the [Rtools news](https://cran.r-project.org/bin/windows/Rtools/rtools43/news.html) if we can't wait.

**Comment by gravesti** [comment]
The Rtools has now been updated 🎉  which seems to fix the main issue. #283

**Comment by mattsecrest** [comment]
@gravesti woah epic catch!
